# Assignment 04 - Pandas

## Company Data Analysis

In this assignment, you will work with the `company_data.csv` dataset to practice various Pandas operations including data loading, cleaning, filtering, and analysis.

**Instructions:** Complete each task by writing your code in the empty cells provided below each question.

## Task 1: Data Loading & Inspection

Load the `company_data.csv` file into a Pandas DataFrame.

**Requirements:**
- Print the first 10 rows of the dataset
- Use a Pandas method to show the data types of each column
- Check for missing values in each column

In [1]:
import pandas as pd

employees = pd.read_csv('C:/Users/Ahmed Wael/.vscode/company_data.csv')
print(employees.head(10))

print()
print(employees.info())

employees.notnull()

   Employee_ID Employee_Name Department    Salary  Years_Experience  \
0          101      John Doe         IT   85000.0                 5
1          102    Jane Smith         HR   60000.0                 3
2          103   Ali Mansour      Sales       NaN                12
3          104      Sara Lee         IT   95000.0                 1
4          105     Ben Clark    Finance   70000.0                 8
5          106     Eva Green      Sales   55000.0                 4
6          107      Mona Ray         HR       NaN                 2
7          108      Leo King         IT  105000.0                10
8          109      Tom Cook    Finance   72000.0                 6
9          110     Anna Bell         IT   88000.0                 9

   Evaluation_Score   Bonus
0                88  5000.0
1                72  3000.0
2                95  7000.0
3                45     NaN
4                60  4000.0
5                82  2000.0
6                55     NaN
7                91  8000.0
8                78  4500.0
9                40  2500.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       20 non-null     int64
 1   Employee_Name     20 non-null     object
 2   Department        20 non-null     object
 3   Salary            18 non-null     float64
 4   Years_Experience  20 non-null     int64
 5   Evaluation_Score  20 non-null     int64
 6   Bonus             18 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.2+ KB
None

,Employee_ID,Employee_Name,Department,Salary,Years_Experience,Evaluation_Score,Bonus
0,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True
2,True,True,True,False,True,True,True
3,True,True,True,True,True,True,False
4,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True
6,True,True,True,False,True,True,False
7,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True

## Task 2: Handling Missing Values

The dataset contains missing values in the `Salary` and `Bonus` columns.

**Requirements:**
- Fill the missing `Salary` values with the median salary of the entire company
- Fill the missing `Bonus` values with 0

In [ ]:

salary_median = employees['Salary'].median()
salary_median

employees['Salary'].fillna(salary_median, inplace=True)

employees['Bonus'].fillna(0, inplace=True)

employees

C:\Users\Ahmed Wael\AppData\Local\Temp\ipykernel_69884\3828614658.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employees['Salary'].fillna(salary_median, inplace=True)
C:\Users\Ahmed Wael\AppData\Local\Temp\ipykernel_69884\3828614658.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employees['Bonus'].fillna(0, inplace=True)

,Employee_ID,Employee_Name,Department,Salary,Years_Experience,Evaluation_Score,Bonus
0,101,John Doe,IT,85000.0,5,88,5000.0
1,102,Jane Smith,HR,60000.0,3,72,3000.0
2,103,Ali Mansour,Sales,73500.0,12,95,7000.0
3,104,Sara Lee,IT,95000.0,1,45,0.0
4,105,Ben Clark,Finance,70000.0,8,60,4000.0
5,106,Eva Green,Sales,55000.0,4,82,2000.0
6,107,Mona Ray,HR,73500.0,2,55,0.0
7,108,Leo King,IT,105000.0,10,91,8000.0
8,109,Tom Cook,Finance,72000.0,6,78,4500.0
9,110,Anna Bell,IT,88000.0,9,40,2500.0
10,111,Ryan Gos,Sales,58000.0,2,65,1500.0
11,112,Emma Stone,HR,62000.0,5,89,3500.0
12,113,Will Smith,IT,92000.0,11,77,6000.0
13,114,Kate Wins,Sales,54000.0,1,30,1000.0
14,115,Jack Spar,Finance,75000.0,7,85,5000.0
15,116,Bruce Wayne,IT,110000.0,15,98,9000.0
16,117,Clark Kent,HR,63000.0,4,70,3200.0
17,118,Diana Prince,Sales,59000.0,3,66,2100.0
18,119,Barry Allen,IT,98000.0,9,81,6500.0
19,120,Hal Jordan,Finance,77000.0,6,74,4800.0

## Task 3: Data Cleaning

The `Employee_Name` column is in the format "FirstName LastName".

**Requirements:**
- Split this column into two new columns: `First_Name` and `Last_Name`
- Delete the original `Employee_Name` column

In [7]:
# import pandas as pd

# employees = pd.read_csv('C:/Users/Ahmed Wael/.vscode/company_data.csv')

employees[['First_Name', 'Last_Name']] = employees['Employee_Name'].str.split(' ', expand=True)

employees.drop('Employee_Name', axis=1, inplace=True)

employees

KeyError: 'Employee_Name'

## Task 4: Filtering

Create a new DataFrame called `Senior_IT`.

**Requirements:**
- The DataFrame should contain only employees from the 'IT' department
- These employees must have more than 8 years of experience

In [24]:
import pandas as pd
employees = pd.read_csv('C:/Users/Ahmed Wael/.vscode/company_data.csv')

senior_it = employees[(employees['Department'] == 'IT') & (employees['Years_Experience'] > 8)]

senior_it

,Employee_ID,Employee_Name,Department,Salary,Years_Experience,Evaluation_Score,Bonus
7,108,Leo King,IT,105000.0,10,91,8000.0
9,110,Anna Bell,IT,88000.0,9,40,2500.0
12,113,Will Smith,IT,92000.0,11,77,6000.0
15,116,Bruce Wayne,IT,110000.0,15,98,9000.0
18,119,Barry Allen,IT,98000.0,9,81,6500.0

## Task 5: Performance Mapping

Create a new column called `Performance_Level` based on the `Evaluation_Score` (1-100).

**Requirements:**
- Score > 80: "High"
- Score 50-80: "Medium"
- Score < 50: "Low"

In [31]:
import pandas as pd
employees = pd.read_csv('C:/Users/Ahmed Wael/.vscode/company_data.csv')

def get_performance(score):
    if score >80:
        return 'High'
    elif score >=50:
        return 'Medium'
    else:
        return 'Low'

employees['Performance_Level']= employees['Evaluation_Score'].apply(get_performance)

employees

,Employee_ID,Employee_Name,Department,Salary,Years_Experience,Evaluation_Score,Bonus,Performance_Level
0,101,John Doe,IT,85000.0,5,88,5000.0,High
1,102,Jane Smith,HR,60000.0,3,72,3000.0,Medium
2,103,Ali Mansour,Sales,NaN,12,95,7000.0,High
3,104,Sara Lee,IT,95000.0,1,45,NaN,Low
4,105,Ben Clark,Finance,70000.0,8,60,4000.0,Medium
5,106,Eva Green,Sales,55000.0,4,82,2000.0,High
6,107,Mona Ray,HR,NaN,2,55,NaN,Medium
7,108,Leo King,IT,105000.0,10,91,8000.0,High
8,109,Tom Cook,Finance,72000.0,6,78,4500.0,Medium
9,110,Anna Bell,IT,88000.0,9,40,2500.0,Low
10,111,Ryan Gos,Sales,58000.0,2,65,1500.0,Medium
11,112,Emma Stone,HR,62000.0,5,89,3500.0,High
12,113,Will Smith,IT,92000.0,11,77,6000.0,Medium
13,114,Kate Wins,Sales,54000.0,1,30,1000.0,Low
14,115,Jack Spar,Finance,75000.0,7,85,5000.0,High
15,116,Bruce Wayne,IT,110000.0,15,98,9000.0,High
16,117,Clark Kent,HR,63000.0,4,70,3200.0,Medium
17,118,Diana Prince,Sales,59000.0,3,66,2100.0,Medium
18,119,Barry Allen,IT,98000.0,9,81,6500.0,High
19,120,Hal Jordan,Finance,77000.0,6,74,4800.0,Medium

## Task 6: Department Statistics

Calculate statistics for each Department.

**Requirements:**
- Calculate the total salary expense for each department
- Calculate the average evaluation score for each department

In [39]:
import pandas as pd
employees = pd.read_csv('C:/Users/Ahmed Wael/.vscode/company_data.csv')

total_salary = employees.groupby('Department')['Salary'].sum().round(2)
average_evaluation = employees.groupby('Department')['Evaluation_Score'].mean().round(2)
print('Total salary for each department\n', total_salary)
print()
print('Average Evaluation Scores for each department\n', average_evaluation)

Total salary for each department
 Department
Finance    294000.0
HR         185000.0
IT         673000.0
Sales      226000.0
Name: Salary, dtype: float64

Average Evaluation Scores for each department
 Department
Finance    74.25
HR         71.50
IT         74.29
Sales      67.60
Name: Evaluation_Score, dtype: float64

## Task 7: Top Earners

Find the top 5 highest-paid employees in the company.

**Requirements:**
- Print only their names and salaries

In [44]:
import pandas as pd
employees = pd.read_csv('C:/Users/Ahmed Wael/.vscode/company_data.csv')

top5 = employees.nlargest(5, 'Salary')[['Employee_Name', 'Salary']]
top5

   Employee_Name    Salary
15   Bruce Wayne  110000.0
7       Leo King  105000.0
18   Barry Allen   98000.0
3       Sara Lee   95000.0
12    Will Smith   92000.0

## Task 8: Salary Update

The company is giving a 10% raise to everyone in the 'Sales' department.

**Requirements:**
- Update the `Salary` column for Sales department employees only
- Apply a 10% increase to their current salary

In [51]:
import pandas as pd
employees = pd.read_csv('C:/Users/Ahmed Wael/.vscode/company_data.csv')

sales_dep = employees['Department']=='Sales'
employees.loc[sales_dep, 'Salary'] = employees.loc[sales_dep,'Salary']*1.1

employees

,Employee_ID,Employee_Name,Department,Salary,Years_Experience,Evaluation_Score,Bonus
0,101,John Doe,IT,85000.0,5,88,5000.0
1,102,Jane Smith,HR,60000.0,3,72,3000.0
2,103,Ali Mansour,Sales,NaN,12,95,7000.0
3,104,Sara Lee,IT,95000.0,1,45,NaN
4,105,Ben Clark,Finance,70000.0,8,60,4000.0
5,106,Eva Green,Sales,60500.0,4,82,2000.0
6,107,Mona Ray,HR,NaN,2,55,NaN
7,108,Leo King,IT,105000.0,10,91,8000.0
8,109,Tom Cook,Finance,72000.0,6,78,4500.0
9,110,Anna Bell,IT,88000.0,9,40,2500.0
10,111,Ryan Gos,Sales,63800.0,2,65,1500.0
11,112,Emma Stone,HR,62000.0,5,89,3500.0
12,113,Will Smith,IT,92000.0,11,77,6000.0
13,114,Kate Wins,Sales,59400.0,1,30,1000.0
14,115,Jack Spar,Finance,75000.0,7,85,5000.0
15,116,Bruce Wayne,IT,110000.0,15,98,9000.0
16,117,Clark Kent,HR,63000.0,4,70,3200.0
17,118,Diana Prince,Sales,64900.0,3,66,2100.0
18,119,Barry Allen,IT,98000.0,9,81,6500.0
19,120,Hal Jordan,Finance,77000.0,6,74,4800.0

## Task 9: Exporting Results

Save the final, cleaned, and updated DataFrame.

**Requirements:**
- Export the DataFrame to a new CSV file
- Name the file `final_employee_report.csv`

In [52]:
import pandas as pd
employees = pd.read_csv('C:/Users/Ahmed Wael/.vscode/company_data.csv')

employees.to_csv('final_employee_report.csv', index=False)